### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by kronoscar** [andersfischernielsen/KovaaK-Visualizer#2]
When I run the program (either through cmd or the batch file) it outputs

`IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed`

and no graphs are created. How do I resolve this?

**Comment by Rycia** [comment]
```
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))
E:\!Steam\steamapps\common\FPSAimTrainer\Visualizer\visualize.py:51: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([datetime.fromtimestamp(tm).strftime('%Y-%m-%d') for tm in xticks],
Traceback (most recent call last):
  File "E:\!Steam\steamapps\common\FPSAimTrainer\Visualizer\visualize.py", line 49, in <module>
    sns.regplot(dates, scores, order=2, label=key, ax=ax)
  File "E:\Python\lib\site-packages\seaborn\regression.py", line 808, in regplot
    plotter = _RegressionPlotter(x, y, data, x_estimator, x_bins, x_ci,
  File "E:\Python\lib\site-packages\seaborn\regression.py", line 116, in __init__
    self.dropna("x", "y", "units", "x_partial", "y_partial")
  File "E:\Python\lib\site-packages\seaborn\regression.py", line 68, in dropna
    setattr(self, var, val[not_na])
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

```
Note: the "E:\Python\lib\site-packages\seaborn\algorithms.py:99: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))" error extends on for.. a while.

The problem here is the same as what exists in the post above me.
